name: Benrila Adventures
favicon: null
layout_spectrum: 0.41883856314234436
typography_spectrum: 0.7064352391753346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5458640658762306
  lightness: 0.5626517774071544
  saturation: 0.2241177666001022
  rhythmicContrast: 0.24280569585971534
purpose: []
